[workspace]
members = [
    "cef-sys",
    "cef",
    "loader",
    "client",
    "renderer",
    "messages",
    "server",
    "cef-api",
    "cef-interface",
    "network",
]

[profile.release]
# lto = true
opt-level = "z"
